### ISSUE TITLE
edna.cz

### ISSUE THREAD

**Issue by xDereCx** [beam-kodi-addons-repository/service.subtitles.edna.cz#1]
edna.cz stopped working recently on my both installs, rpi2 + ubuntu with kodi, guess there are some changes on edna website

**Comment by xDereCx** [comment]
sry checked once more, plugin is not working only for Marvels Agents Of S.H.I.E.L.D, dont know why :)

**Comment by ondrejbima** [comment]
Aha, zkusim, kouknu :)

**Comment by ondrejbima** [comment]
Dostavas chybu, nebo se titulky "jenom" nenajdou?

**Comment by ondrejbima** [comment]
Jestli jenom nehleda, tak je potreba si show prejmenovat z Marvel's Agents of S.H.I.E.L.D. na Agents of S.H.I.E.L.D.

**Comment by xDereCx** [comment]
no neviem nebezi mi to ani na hawai five-0 momentalne, skusim spravit debug ked bude chvilka

**Comment by ondrejbima** [comment]
titulky nejsou na edna.cz, je to jen link na titulky.com..
